name: github page
on:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: 2e8eba0fdc0a36508b087ad4df854971b4e4c354
        BRANCH: master
        FOLDER: .